import * as THREE from 'three';
import { CHUNK,WORLD_HEIGHT,RENDER_DIST,AIR,WATER,TORCH } from './config.js';
import { scene,loadedChunks,modifiedBlocks } from './state.js';
import { atlasTexture,getAtlasIndex,AT } from './textures.js';
import { generateChunkData } from './worldgen.js';
const solidMat=new THREE.MeshLambertMaterial({map:atlasTexture,alphaTest:0.5}),waterMat=new THREE.MeshLambertMaterial({color:0x3a6db8,transparent:true,opacity:0.7}),torchMat=new THREE.MeshBasicMaterial({map:atlasTexture,alphaTest:0.5});
const FACES=[{n:[1,0,0],c:[[1,0,1],[1,0,0],[1,1,0],[1,1,1]],uv:[[0,0],[1,0],[1,1],[0,1]]},{n:[-1,0,0],c:[[0,0,0],[0,0,1],[0,1,1],[0,1,0]],uv:[[0,0],[1,0],[1,1],[0,1]]},{n:[0,1,0],c:[[0,1,1],[1,1,1],[1,1,0],[0,1,0]],uv:[[0,0],[1,0],[1,1],[0,1]]},{n:[0,-1,0],c:[[0,0,0],[1,0,0],[1,0,1],[0,0,1]],uv:[[0,0],[1,0],[1,1],[0,1]]},{n:[0,0,1],c:[[0,0,1],[1,0,1],[1,1,1],[0,1,1]],uv:[[0,0],[1,0],[1,1],[0,1]]},{n:[0,0,-1],c:[[1,0,0],[0,0,0],[0,1,0],[1,1,0]],uv:[[0,0],[1,0],[1,1],[0,1]]}];
const PIXEL_INSET=0.5/(8*16);
export function getChunkData(cx,cz){const key=cx+','+cz;if(!loadedChunks.has(key))loadedChunks.set(key,{meshes:[],data:generateChunkData(cx,cz)});return loadedChunks.get(key).data;}
export function buildChunkMesh(cx,cz){const key=cx+','+cz,entry=loadedChunks.get(key);if(!entry)return;for(const m of entry.meshes){scene.remove(m);m.geometry.dispose();}entry.meshes=[];const data=entry.data,getB=(x,y,z)=>(x<0||x>=CHUNK||y<0||y>=WORLD_HEIGHT||z<0||z>=CHUNK)?AIR:data[x+z*CHUNK+y*CHUNK*CHUNK],isOp=b=>b!==AIR&&b!==WATER,solid={p:[],uv:[],n:[],i:[]},water={p:[],n:[],i:[]},torch={p:[],uv:[],n:[],i:[]};
for(let y=0;y<WORLD_HEIGHT;y++)for(let z=0;z<CHUNK;z++)for(let x=0;x<CHUNK;x++){const b=getB(x,y,z);if(b===AIR)continue;const isW=b===WATER,isT=b===TORCH,T=isT?torch:(isW?water:solid);for(let fi=0;fi<6;fi++){const F=FACES[fi],nb=getB(x+F.n[0],y+F.n[1],z+F.n[2]);if(isT){}else if(isW){if(nb!==AIR&&nb!==WATER)continue;}else{if(isOp(nb))continue;}const base=T.p.length/3,bx0=cx*CHUNK+x,bz0=cz*CHUNK+z;if(isW){for(let k=0;k<4;k++){const v3=F.c[k];T.p.push(bx0+v3[0],y+v3[1],bz0+v3[2]);T.n.push(F.n[0],F.n[1],F.n[2]);}}else if(isT){const cxm=bx0+0.5,czm=bz0+0.5,scaleXZ=0.15,scaleY=0.7;for(let k=0;k<4;k++){const v3=F.c[k];T.p.push(cxm+(v3[0]-0.5)*scaleXZ,y+v3[1]*scaleY,czm+(v3[2]-0.5)*scaleXZ);T.n.push(F.n[0],F.n[1],F.n[2]);}const ai=AT.TORCH,col=ai%8,row=Math.floor(ai/8),uMin=col/8+PIXEL_INSET,uMax=(col+1)/8-PIXEL_INSET,vMin=1-(row+1)/8+PIXEL_INSET,vMax=1-row/8-PIXEL_INSET,uR=uMax-uMin,vR=vMax-vMin;for(let k=0;k<4;k++){const uvL=F.uv[k];T.uv.push(uMin+uvL[0]*uR,vMin+uvL[1]*vR);}}else{const ai=getAtlasIndex(b,fi),col=ai%8,row=Math.floor(ai/8),uMin=col/8+PIXEL_INSET,uMax=(col+1)/8-PIXEL_INSET,vMin=1-(row+1)/8+PIXEL_INSET,vMax=1-row/8-PIXEL_INSET,uR=uMax-uMin,vR=vMax-vMin;for(let k=0;k<4;k++){const v3=F.c[k];T.p.push(bx0+v3[0],y+v3[1],bz0+v3[2]);T.n.push(F.n[0],F.n[1],F.n[2]);const uvL=F.uv[k];T.uv.push(uMin+uvL[0]*uR,vMin+uvL[1]*vR);}}T.i.push(base,base+1,base+2,base,base+2,base+3);}}
const mk=(T,mat)=>{if(T.i.length===0)return null;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(T.p,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(T.n,3));if(T.uv.length)g.setAttribute('uv',new THREE.Float32BufferAttribute(T.uv,2));g.setIndex(T.i);return new THREE.Mesh(g,mat);};const s=mk(solid,solidMat),w=mk(water,waterMat),t=mk(torch,torchMat);if(s){scene.add(s);entry.meshes.push(s);}if(w){scene.add(w);entry.meshes.push(w);}if(t){scene.add(t);entry.meshes.push(t);}}
export function updateChunks(px,pz){const pcx=Math.floor(px/CHUNK),pcz=Math.floor(pz/CHUNK);for(let dx=-RENDER_DIST;dx<=RENDER_DIST;dx++)for(let dz=-RENDER_DIST;dz<=RENDER_DIST;dz++){const cx=pcx+dx,cz=pcz+dz,key=cx+','+cz;if(!loadedChunks.has(key)){getChunkData(cx,cz);buildChunkMesh(cx,cz);}}for(const[key,entry]of loadedChunks){const[cx,cz]=key.split(',').map(Number);if(Math.abs(cx-pcx)>RENDER_DIST+2||Math.abs(cz-pcz)>RENDER_DIST+2){for(const m of entry.meshes){scene.remove(m);m.geometry.dispose();}loadedChunks.delete(key);}}}
export function getBlockWorld(wx,wy,wz){if(wy<0||wy>=WORLD_HEIGHT)return AIR;const cx=Math.floor(wx/CHUNK),cz=Math.floor(wz/CHUNK),data=getChunkData(cx,cz),lx=((wx%CHUNK)+CHUNK)%CHUNK,lz=((wz%CHUNK)+CHUNK)%CHUNK;return data[lx+lz*CHUNK+wy*CHUNK*CHUNK];}
export function setBlockWorld(wx,wy,wz,v){if(wy<0||wy>=WORLD_HEIGHT)return;const cx=Math.floor(wx/CHUNK),cz=Math.floor(wz/CHUNK),data=getChunkData(cx,cz),lx=((wx%CHUNK)+CHUNK)%CHUNK,lz=((wz%CHUNK)+CHUNK)%CHUNK;data[lx+lz*CHUNK+wy*CHUNK*CHUNK]=v;modifiedBlocks.set(wx+','+wy+','+wz,v);}
export function markDirty(wx,wy,wz){const cx=Math.floor(wx/CHUNK),cz=Math.floor(wz/CHUNK),set=new Set([cx+','+cz]);if(wx%CHUNK===0)set.add((cx-1)+','+cz);if(wx%CHUNK===CHUNK-1)set.add((cx+1)+','+cz);if(wz%CHUNK===0)set.add(cx+','+(cz-1));if(wz%CHUNK===CHUNK-1)set.add(cx+','+(cz+1));for(const k of set){const[ccx,ccz]=k.split(',').map(Number);if(loadedChunks.has(k))buildChunkMesh(ccx,ccz);}}