import * as THREE from 'three';
import { state,player,mobs,sun,scene } from './state.js';
import { isTouch,settings,BIOME_NAMES,DAY_LENGTH } from './config.js';
import { getInventoryCount,HOTBAR,G } from './inventory.js';
let fps=0,fpsT=0,fpsN=0;export function getFps(){return fps;}export function updateFps(dt){fpsN++;fpsT+=dt;if(fpsT>=0.5){fps=Math.round(fpsN/fpsT);fpsN=0;fpsT=0;}}
export function notify(msg){const el=document.getElementById('notify');el.textContent=msg;el.classList.add('show');clearTimeout(notify._t);notify._t=setTimeout(()=>el.classList.remove('show'),2200);}G.notify=notify;
function drawHeart(ctx,color){ctx.fillStyle=color;const px=[[3,2],[4,2],[5,2],[6,2],[9,2],[10,2],[11,2],[12,2],[2,3],[3,3],[4,3],[5,3],[6,3],[7,3],[8,3],[9,3],[10,3],[11,3],[12,3],[13,3],[2,4],[3,4],[4,4],[5,4],[6,4],[7,4],[8,4],[9,4],[10,4],[11,4],[12,4],[13,4],[2,5],[3,5],[4,5],[5,5],[6,5],[7,5],[8,5],[9,5],[10,5],[11,5],[12,5],[13,5],[3,6],[4,6],[5,6],[6,6],[7,6],[8,6],[9,6],[10,6],[11,6],[12,6],[4,7],[5,7],[6,7],[7,7],[8,7],[9,7],[10,7],[11,7],[5,8],[6,8],[7,8],[8,8],[9,8],[10,8],[6,9],[7,9],[8,9],[9,9],[7,10],[8,10]];for(const[x,y]of px)ctx.fillRect(x,y,1,1);}
function drawHalfHeart(ctx,color){drawHeart(ctx,'#3a0000');ctx.fillStyle=color;const px=[[3,2],[4,2],[5,2],[6,2],[2,3],[3,3],[4,3],[5,3],[6,3],[7,3],[2,4],[3,4],[4,4],[5,4],[6,4],[7,4],[2,5],[3,5],[4,5],[5,5],[6,5],[7,5],[3,6],[4,6],[5,6],[6,6],[7,6],[4,7],[5,7],[6,7],[7,7],[5,8],[6,8],[7,8],[6,9],[7,9]];for(const[x,y]of px)ctx.fillRect(x,y,1,1);}
export function updateHealthBar(){const bar=document.getElementById('health-bar');if(state.gameMode==='creative'){bar.innerHTML='';bar.style.display='none';return;}bar.style.display='flex';bar.innerHTML='';const hearts=Math.ceil(player.maxHealth/2);for(let i=0;i<hearts;i++){const c=document.createElement('canvas');c.width=16;c.height=16;c.className='heart';const ctx=c.getContext('2d'),hp=player.health-i*2;drawHeart(ctx,'#3a0000');if(hp>=2)drawHeart(ctx,'#ff2222');else if(hp>=1)drawHalfHeart(ctx,'#ff2222');bar.appendChild(c);}if(G.updateEatBtn)G.updateEatBtn();}G.updateHealthBar=updateHealthBar;
export function damagePlayer(amount){if(player.dead||player.hurtCooldown>0||state.gameMode==='creative')return;player.health-=amount;player.hurtCooldown=0.5;if(navigator.vibrate&&settings.vibration){try{navigator.vibrate(40);}catch(e){}}import('./audio.js').then(m=>m.Snd.hurt());const dmg=document.getElementById('damage-overlay');dmg.style.opacity='1';setTimeout(()=>{dmg.style.opacity='0';},200);updateHealthBar();if(player.health<=0)killPlayer();}
export function killPlayer(){player.dead=true;player.health=0;document.getElementById('death-screen').style.display='flex';if(document.pointerLockElement)document.exitPointerLock();}
export function isNightTime(){return state.worldTime%DAY_LENGTH>DAY_LENGTH/2;}
const dayColors={day:new THREE.Color(0x87CEEB),night:new THREE.Color(0x0a0f1a),dusk:new THREE.Color(0xff8855),dawn:new THREE.Color(0xffaa66)};function getSunAngle(){return(state.worldTime/DAY_LENGTH)*Math.PI*2;}
export function updateSky(){const a=getSunAngle(),elevation=Math.sin(a);sun.position.set(Math.cos(a)*100,elevation*100,Math.sin(a)*50);let bgColor;if(elevation>0.3)bgColor=dayColors.day.clone();else if(elevation<-0.2)bgColor=dayColors.night.clone();else{const t=(elevation+0.2)/0.5,c=elevation>0?dayColors.dawn:dayColors.dusk;bgColor=dayColors.night.clone().lerp(c,t);if(elevation>0)bgColor.lerp(dayColors.day,elevation/0.3);}scene.background.copy(bgColor);scene.fog.color.copy(bgColor);sun.intensity=Math.max(0.15,0.75+elevation*0.5)*0.9;}
export function updateInfoDisplay(){const infoEl=document.getElementById('info'),bx=Math.floor(player.pos.x),by=Math.floor(player.pos.y),bz=Math.floor(player.pos.z),held=HOTBAR[state.selected],name=held?held.name:'?',isN=isNightTime(),timeIcon=isN?'🌙':'☀️',phase=state.worldTime%DAY_LENGTH,isDay=phase<DAY_LENGTH/2,remain=isDay?DAY_LENGTH/2-phase:DAY_LENGTH-phase,mm=Math.floor(remain/60),ss=Math.floor(remain%60),modeIcon=state.gameMode==='creative'?'🎨':'⚔️';infoEl.innerHTML=modeIcon+' 📍 '+bx+' '+by+' '+bz+' '+timeIcon+' '+mm+':'+(ss<10?'0':'')+ss+'<br>🎯 '+name+' ('+getInventoryCount(held?held.id:0)+')<br>'+(player.fly?'✈ on':'✈ off')+' | FPS: '+fps+' | Mobs: '+mobs.length;}
export function showMenu(){const menuEl=document.getElementById('menu');menuEl.style.display='flex';document.body.classList.remove('playing');if(document.pointerLockElement)document.exitPointerLock();const hasSave=!!localStorage.getItem('mc_clone_world');document.getElementById('menu-continue').classList.toggle('disabled',!hasSave);}
export function hideMenu(){document.getElementById('menu').style.display='none';document.body.classList.add('playing');}export { isTouch };